version: '3.8'

services:
  approveit_db:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DB=approveit
    volumes:
      - approveit_db_data:/bitnami/postgresql

  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - approveit_redis_data:/bitnami/redis

volumes:
  approveit_db_data:
  approveit_redis_data: